/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agendamata55;


import com.mycompany.agendamata55.classes.Agenda;
import com.mycompany.agendamata55.classes.Contato;
import com.mycompany.agendamata55.classes.ContatoBasico;
import com.mycompany.agendamata55.classes.EContato;
import com.mycompany.agendamata55.classes.Telefone;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sousa
 */
public final class principal extends javax.swing.JFrame {
    int anoFixo = 0, mesFixo = 0, diaFixo = 0;
    int anoAltera = 0, mesAltera =0, diaAltera = 0;
    int valorSelecao = 0;
    int diaClick = 0;
    
    
    static void mostraDados(ContatoBasico obj) {
		System.out.println(obj.getDados());
		if (obj instanceof Contato)
			System.out.println(((Contato) obj).getIdade());
		System.out.println("xxxxxxxxxxxxxxxxxxxxxxxxxx");
	}

	
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        iniciaCalendario();
        calendario();
        calendarioEventosMouse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        selecaoMes = new javax.swing.JComboBox<>();
        selecaoAno = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        domFixo = new javax.swing.JLabel();
        segFixo = new javax.swing.JLabel();
        terFixo = new javax.swing.JLabel();
        quaFixo = new javax.swing.JLabel();
        sexFixo = new javax.swing.JLabel();
        quiFixo = new javax.swing.JLabel();
        sabFixo = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        d9 = new javax.swing.JLabel();
        d10 = new javax.swing.JLabel();
        d11 = new javax.swing.JLabel();
        d12 = new javax.swing.JLabel();
        d13 = new javax.swing.JLabel();
        d14 = new javax.swing.JLabel();
        d15 = new javax.swing.JLabel();
        d16 = new javax.swing.JLabel();
        d17 = new javax.swing.JLabel();
        d18 = new javax.swing.JLabel();
        d19 = new javax.swing.JLabel();
        d20 = new javax.swing.JLabel();
        d21 = new javax.swing.JLabel();
        d22 = new javax.swing.JLabel();
        d23 = new javax.swing.JLabel();
        d24 = new javax.swing.JLabel();
        d25 = new javax.swing.JLabel();
        d26 = new javax.swing.JLabel();
        d27 = new javax.swing.JLabel();
        d28 = new javax.swing.JLabel();
        d29 = new javax.swing.JLabel();
        d30 = new javax.swing.JLabel();
        d31 = new javax.swing.JLabel();
        d32 = new javax.swing.JLabel();
        d33 = new javax.swing.JLabel();
        d34 = new javax.swing.JLabel();
        d35 = new javax.swing.JLabel();
        d36 = new javax.swing.JLabel();
        d37 = new javax.swing.JLabel();
        d38 = new javax.swing.JLabel();
        d39 = new javax.swing.JLabel();
        d40 = new javax.swing.JLabel();
        d41 = new javax.swing.JLabel();
        d42 = new javax.swing.JLabel();
        anoPagina = new javax.swing.JLabel();
        semanaPagina = new javax.swing.JLabel();
        diaPagina = new javax.swing.JLabel();
        mesPagina = new javax.swing.JLabel();
        botaoVoltaDiaAtual = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        compromisso1 = new javax.swing.JTextField();
        compromisso6 = new javax.swing.JTextField();
        compromisso5 = new javax.swing.JTextField();
        compromisso4 = new javax.swing.JTextField();
        compromisso3 = new javax.swing.JTextField();
        compromisso2 = new javax.swing.JTextField();
        compromisso7 = new javax.swing.JTextField();
        botaoSalvaCompromissos = new javax.swing.JButton();
        botaoDeleteCompromisso1 = new javax.swing.JButton();
        botaoDeleteCompromisso2 = new javax.swing.JButton();
        botaoDeleteCompromisso3 = new javax.swing.JButton();
        botaoDeleteCompromisso4 = new javax.swing.JButton();
        botaoDeleteCompromisso5 = new javax.swing.JButton();
        botaoDeleteCompromisso6 = new javax.swing.JButton();
        botaoDeleteCompromisso7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        selecaoMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro" }));
        selecaoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecaoMesActionPerformed(evt);
            }
        });

        selecaoAno.setEditable(true);
        selecaoAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        selecaoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecaoAnoActionPerformed(evt);
            }
        });

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        domFixo.setBackground(new java.awt.Color(204, 204, 204));
        domFixo.setForeground(new java.awt.Color(255, 51, 51));
        domFixo.setText("Dom");

        segFixo.setText("Seg");

        terFixo.setText("Ter");

        quaFixo.setText("Qua");

        sexFixo.setText("Sex");

        quiFixo.setText("Qui");

        sabFixo.setText("Sab");

        d1.setForeground(new java.awt.Color(255, 51, 51));
        d1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d1.setText("00");

        d2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d2.setText("00");

        d3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d3.setText("00");

        d5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d5.setText("00");

        d4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d4.setText("00");

        d6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d6.setText("00");

        d7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d7.setText("00");

        d8.setForeground(new java.awt.Color(255, 51, 51));
        d8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d8.setText("00");

        d9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d9.setText("00");

        d10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d10.setText("00");

        d11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d11.setText("00");

        d12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d12.setText("00");

        d13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d13.setText("00");

        d14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d14.setText("00");

        d15.setForeground(new java.awt.Color(255, 51, 51));
        d15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d15.setText("00");

        d16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d16.setText("00");

        d17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d17.setText("00");

        d18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d18.setText("00");

        d19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d19.setText("00");

        d20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d20.setText("00");

        d21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d21.setText("00");

        d22.setForeground(new java.awt.Color(255, 51, 51));
        d22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d22.setText("00");

        d23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d23.setText("00");

        d24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d24.setText("00");

        d25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d25.setText("00");

        d26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d26.setText("00");

        d27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d27.setText("00");

        d28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d28.setText("00");

        d29.setForeground(new java.awt.Color(255, 51, 51));
        d29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d29.setText("00");

        d30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d30.setText("00");

        d31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d31.setText("00");

        d32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d32.setText("00");

        d33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d33.setText("00");

        d34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d34.setText("00");

        d35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d35.setText("00");

        d36.setForeground(new java.awt.Color(255, 51, 51));
        d36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d36.setText("00");

        d37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d37.setText("00");

        d38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d38.setText("00");

        d39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d39.setText("00");

        d40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d40.setText("00");

        d41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d41.setText("00");

        d42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d42.setText("00");

        jLayeredPane2.setLayer(selecaoMes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(selecaoAno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSpinner1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(domFixo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(segFixo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(terFixo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(quaFixo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(sexFixo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(quiFixo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(sabFixo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(d42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(domFixo)
                                        .addGap(18, 18, 18)
                                        .addComponent(segFixo)
                                        .addGap(18, 18, 18)
                                        .addComponent(terFixo)
                                        .addGap(18, 18, 18)
                                        .addComponent(quaFixo)
                                        .addGap(18, 18, 18)
                                        .addComponent(quiFixo))
                                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(selecaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(sexFixo)
                                        .addGap(18, 18, 18)
                                        .addComponent(sabFixo))
                                    .addComponent(selecaoAno, 0, 1, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(d8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(d15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(d22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(d29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d32, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d33, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d34, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d35, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(d36, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d38, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d39, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d40, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d41, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d42, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domFixo)
                    .addComponent(segFixo)
                    .addComponent(terFixo)
                    .addComponent(quaFixo)
                    .addComponent(sexFixo)
                    .addComponent(quiFixo)
                    .addComponent(sabFixo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d7)
                    .addComponent(d6)
                    .addComponent(d5)
                    .addComponent(d4)
                    .addComponent(d3)
                    .addComponent(d2)
                    .addComponent(d1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d14)
                    .addComponent(d13)
                    .addComponent(d12)
                    .addComponent(d11)
                    .addComponent(d10)
                    .addComponent(d9)
                    .addComponent(d8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d21)
                    .addComponent(d20)
                    .addComponent(d19)
                    .addComponent(d18)
                    .addComponent(d17)
                    .addComponent(d16)
                    .addComponent(d15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d28)
                    .addComponent(d27)
                    .addComponent(d26)
                    .addComponent(d25)
                    .addComponent(d24)
                    .addComponent(d23)
                    .addComponent(d22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d35)
                    .addComponent(d34)
                    .addComponent(d33)
                    .addComponent(d32)
                    .addComponent(d31)
                    .addComponent(d30)
                    .addComponent(d29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d42)
                    .addComponent(d41)
                    .addComponent(d40)
                    .addComponent(d39)
                    .addComponent(d38)
                    .addComponent(d37)
                    .addComponent(d36))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jLayeredPane2);
        jLayeredPane2.setBounds(80, 100, 271, 190);

        anoPagina.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        anoPagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anoPagina.setText("ano");
        jLayeredPane1.add(anoPagina);
        anoPagina.setBounds(400, 90, 280, 79);

        semanaPagina.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        semanaPagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        semanaPagina.setText("semana");
        jLayeredPane1.add(semanaPagina);
        semanaPagina.setBounds(560, 220, 290, 41);

        diaPagina.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        diaPagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diaPagina.setText("dia");
        jLayeredPane1.add(diaPagina);
        diaPagina.setBounds(610, 160, 200, 40);

        mesPagina.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mesPagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesPagina.setText("mes");
        jLayeredPane1.add(mesPagina);
        mesPagina.setBounds(610, 110, 180, 32);

        botaoVoltaDiaAtual.setIcon(new javax.swing.ImageIcon("C:\\Users\\sousa\\OneDrive\\Área de Trabalho\\mata55\\New folder\\AGENDAFULLSTACK\\agendaMATA55\\15766.png")); // NOI18N
        botaoVoltaDiaAtual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoVoltaDiaAtualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoVoltaDiaAtualMouseExited(evt);
            }
        });
        botaoVoltaDiaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltaDiaAtualActionPerformed(evt);
            }
        });
        jLayeredPane1.add(botaoVoltaDiaAtual);
        botaoVoltaDiaAtual.setBounds(360, 100, 60, 60);
        jLayeredPane1.add(jSeparator1);
        jSeparator1.setBounds(100, 410, 680, 30);
        jLayeredPane1.add(jSeparator2);
        jSeparator2.setBounds(100, 330, 680, 30);
        jLayeredPane1.add(jSeparator3);
        jSeparator3.setBounds(100, 370, 680, 30);
        jLayeredPane1.add(jSeparator4);
        jSeparator4.setBounds(100, 450, 680, 30);
        jLayeredPane1.add(jSeparator5);
        jSeparator5.setBounds(100, 490, 680, 30);
        jLayeredPane1.add(jSeparator6);
        jSeparator6.setBounds(100, 530, 680, 30);
        jLayeredPane1.add(jSeparator8);
        jSeparator8.setBounds(100, 570, 680, 30);

        compromisso1.setBorder(null);
        compromisso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compromisso1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compromisso1MouseExited(evt);
            }
        });
        compromisso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compromisso1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(compromisso1);
        compromisso1.setBounds(100, 310, 680, 20);

        compromisso6.setBorder(null);
        compromisso6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compromisso6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compromisso6MouseExited(evt);
            }
        });
        jLayeredPane1.add(compromisso6);
        compromisso6.setBounds(100, 510, 680, 20);

        compromisso5.setBorder(null);
        compromisso5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compromisso5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compromisso5MouseExited(evt);
            }
        });
        jLayeredPane1.add(compromisso5);
        compromisso5.setBounds(100, 470, 680, 20);

        compromisso4.setBorder(null);
        compromisso4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compromisso4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compromisso4MouseExited(evt);
            }
        });
        jLayeredPane1.add(compromisso4);
        compromisso4.setBounds(100, 430, 680, 20);

        compromisso3.setBorder(null);
        compromisso3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compromisso3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compromisso3MouseExited(evt);
            }
        });
        jLayeredPane1.add(compromisso3);
        compromisso3.setBounds(100, 390, 680, 20);

        compromisso2.setBorder(null);
        compromisso2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compromisso2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compromisso2MouseExited(evt);
            }
        });
        jLayeredPane1.add(compromisso2);
        compromisso2.setBounds(100, 350, 680, 20);

        compromisso7.setBorder(null);
        compromisso7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compromisso7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compromisso7MouseExited(evt);
            }
        });
        compromisso7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compromisso7ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(compromisso7);
        compromisso7.setBounds(100, 550, 680, 20);

        botaoSalvaCompromissos.setIcon(new javax.swing.ImageIcon("C:\\Users\\sousa\\OneDrive\\Área de Trabalho\\mata55\\New folder\\AGENDAFULLSTACK\\agendaMATA55\\botaosalvar.png")); // NOI18N
        botaoSalvaCompromissos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoSalvaCompromissosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoSalvaCompromissosMouseExited(evt);
            }
        });
        botaoSalvaCompromissos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvaCompromissosActionPerformed(evt);
            }
        });
        jLayeredPane1.add(botaoSalvaCompromissos);
        botaoSalvaCompromissos.setBounds(360, 230, 60, 60);

        botaoDeleteCompromisso1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sousa\\OneDrive\\Área de Trabalho\\mata55\\New folder\\AGENDAFULLSTACK\\agendaMATA55\\botaodelete.png")); // NOI18N
        botaoDeleteCompromisso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso1MouseExited(evt);
            }
        });
        botaoDeleteCompromisso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteCompromisso1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(botaoDeleteCompromisso1);
        botaoDeleteCompromisso1.setBounds(800, 300, 30, 30);

        botaoDeleteCompromisso2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sousa\\OneDrive\\Área de Trabalho\\mata55\\New folder\\AGENDAFULLSTACK\\agendaMATA55\\botaodelete.png")); // NOI18N
        botaoDeleteCompromisso2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso2MouseExited(evt);
            }
        });
        botaoDeleteCompromisso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteCompromisso2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(botaoDeleteCompromisso2);
        botaoDeleteCompromisso2.setBounds(800, 340, 30, 30);

        botaoDeleteCompromisso3.setIcon(new javax.swing.ImageIcon("C:\\Users\\sousa\\OneDrive\\Área de Trabalho\\mata55\\New folder\\AGENDAFULLSTACK\\agendaMATA55\\botaodelete.png")); // NOI18N
        botaoDeleteCompromisso3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso3MouseExited(evt);
            }
        });
        botaoDeleteCompromisso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteCompromisso3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(botaoDeleteCompromisso3);
        botaoDeleteCompromisso3.setBounds(800, 380, 30, 30);

        botaoDeleteCompromisso4.setIcon(new javax.swing.ImageIcon("C:\\Users\\sousa\\OneDrive\\Área de Trabalho\\mata55\\New folder\\AGENDAFULLSTACK\\agendaMATA55\\botaodelete.png")); // NOI18N
        botaoDeleteCompromisso4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso4MouseExited(evt);
            }
        });
        botaoDeleteCompromisso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteCompromisso4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(botaoDeleteCompromisso4);
        botaoDeleteCompromisso4.setBounds(800, 420, 30, 30);

        botaoDeleteCompromisso5.setIcon(new javax.swing.ImageIcon("C:\\Users\\sousa\\OneDrive\\Área de Trabalho\\mata55\\New folder\\AGENDAFULLSTACK\\agendaMATA55\\botaodelete.png")); // NOI18N
        botaoDeleteCompromisso5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso5MouseExited(evt);
            }
        });
        botaoDeleteCompromisso5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteCompromisso5ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(botaoDeleteCompromisso5);
        botaoDeleteCompromisso5.setBounds(800, 460, 30, 30);

        botaoDeleteCompromisso6.setIcon(new javax.swing.ImageIcon("C:\\Users\\sousa\\OneDrive\\Área de Trabalho\\mata55\\New folder\\AGENDAFULLSTACK\\agendaMATA55\\botaodelete.png")); // NOI18N
        botaoDeleteCompromisso6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso6MouseExited(evt);
            }
        });
        botaoDeleteCompromisso6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteCompromisso6ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(botaoDeleteCompromisso6);
        botaoDeleteCompromisso6.setBounds(800, 500, 30, 30);

        botaoDeleteCompromisso7.setIcon(new javax.swing.ImageIcon("C:\\Users\\sousa\\OneDrive\\Área de Trabalho\\mata55\\New folder\\AGENDAFULLSTACK\\agendaMATA55\\botaodelete.png")); // NOI18N
        botaoDeleteCompromisso7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoDeleteCompromisso7MouseExited(evt);
            }
        });
        botaoDeleteCompromisso7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteCompromisso7ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(botaoDeleteCompromisso7);
        botaoDeleteCompromisso7.setBounds(800, 540, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sousa\\OneDrive\\Área de Trabalho\\mata55\\New folder\\AGENDAFULLSTACK\\agendaMATA55\\fundo.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(10, 0, 900, 710);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 900, 710);

        setBounds(0, 0, 916, 704);
    }// </editor-fold>//GEN-END:initComponents

    private void selecaoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecaoMesActionPerformed
        
        diaAltera = diaFixo;
        calendario();

    }//GEN-LAST:event_selecaoMesActionPerformed

    private void selecaoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecaoAnoActionPerformed
        try {
            int a = Integer.parseInt(selecaoAno.getSelectedItem().toString());
            diaAltera = diaFixo;
            calendario();
            anoPagina.setText(selecaoAno.getSelectedItem().toString());
        } catch (NumberFormatException e) {
            selecaoAno.setSelectedItem(anoFixo);
        }
        
    }//GEN-LAST:event_selecaoAnoActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        valorSelecao = Integer.parseInt(jSpinner1.getValue().toString());
        int a = selecaoMes.getSelectedIndex();
        int ano = Integer.parseInt(selecaoAno.getSelectedItem().toString());
        
        if (valorSelecao == -1){
            if (selecaoMes.getSelectedIndex() != 11){
                selecaoMes.setSelectedIndex(a+1);
            } else {
                selecaoMes.setSelectedIndex(0);
                ano += 1;
                selecaoAno.setSelectedItem(ano);
            }          
        }
        if (valorSelecao == 1){
            if (selecaoMes.getSelectedIndex() != 0){
                selecaoMes.setSelectedIndex(a-1);
            } else {
                selecaoMes.setSelectedIndex(0);
                ano -= 1;
                selecaoAno.setSelectedItem(ano);
            }          
        }        
        jSpinner1.setValue(0);
        
    }//GEN-LAST:event_jSpinner1StateChanged

    private void botaoVoltaDiaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltaDiaAtualActionPerformed
        iniciaCalendario();
        calendario();
        
    }//GEN-LAST:event_botaoVoltaDiaAtualActionPerformed

    private void botaoVoltaDiaAtualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltaDiaAtualMouseEntered
      
    }//GEN-LAST:event_botaoVoltaDiaAtualMouseEntered

    private void botaoVoltaDiaAtualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltaDiaAtualMouseExited
     
    }//GEN-LAST:event_botaoVoltaDiaAtualMouseExited

    private void compromisso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compromisso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compromisso1ActionPerformed

    private void compromisso1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso1MouseEntered
        compromisso1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_compromisso1MouseEntered

    private void compromisso1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso1MouseExited
        compromisso1.setBorder(null);
    }//GEN-LAST:event_compromisso1MouseExited

    private void compromisso2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso2MouseEntered
         compromisso2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_compromisso2MouseEntered

    private void compromisso2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso2MouseExited
          compromisso2.setBorder(null);
    }//GEN-LAST:event_compromisso2MouseExited

    private void compromisso3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso3MouseEntered
         compromisso3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_compromisso3MouseEntered

    private void compromisso3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso3MouseExited
         compromisso3.setBorder(null);
    }//GEN-LAST:event_compromisso3MouseExited

    private void compromisso4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso4MouseEntered
         compromisso4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_compromisso4MouseEntered

    private void compromisso4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso4MouseExited
          compromisso4.setBorder(null);
    }//GEN-LAST:event_compromisso4MouseExited

    private void compromisso5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso5MouseEntered
         compromisso5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_compromisso5MouseEntered

    private void compromisso5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso5MouseExited
          compromisso5.setBorder(null);
    }//GEN-LAST:event_compromisso5MouseExited

    private void compromisso6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso6MouseEntered
         compromisso6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_compromisso6MouseEntered

    private void compromisso6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso6MouseExited
         compromisso6.setBorder(null);
    }//GEN-LAST:event_compromisso6MouseExited

    private void compromisso7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso7MouseEntered
        compromisso7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_compromisso7MouseEntered

    private void compromisso7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compromisso7MouseExited
         compromisso7.setBorder(null);
    }//GEN-LAST:event_compromisso7MouseExited

    private void compromisso7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compromisso7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compromisso7ActionPerformed

    private void botaoSalvaCompromissosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSalvaCompromissosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSalvaCompromissosMouseEntered

    private void botaoSalvaCompromissosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSalvaCompromissosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSalvaCompromissosMouseExited
    private void botaoSalvaCompromissosMouseClicked(java.awt.event.MouseEvent evt) {                                                    
        Agenda a = new Agenda();
        a.adicionar(anoAltera, mesAltera, diaAltera,compromisso1.getText());
    }
    private void botaoSalvaCompromissosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvaCompromissosActionPerformed
        
    }//GEN-LAST:event_botaoSalvaCompromissosActionPerformed

    private void botaoDeleteCompromisso1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso1MouseEntered

    private void botaoDeleteCompromisso1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso1MouseExited

    private void botaoDeleteCompromisso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso1ActionPerformed

    private void botaoDeleteCompromisso2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso2MouseEntered

    private void botaoDeleteCompromisso2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso2MouseExited

    private void botaoDeleteCompromisso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso2ActionPerformed

    private void botaoDeleteCompromisso3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso3MouseEntered

    private void botaoDeleteCompromisso3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso3MouseExited

    private void botaoDeleteCompromisso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso3ActionPerformed

    private void botaoDeleteCompromisso4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso4MouseEntered

    private void botaoDeleteCompromisso4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso4MouseExited

    private void botaoDeleteCompromisso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso4ActionPerformed

    private void botaoDeleteCompromisso5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso5MouseEntered

    private void botaoDeleteCompromisso5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso5MouseExited

    private void botaoDeleteCompromisso5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso5ActionPerformed

    private void botaoDeleteCompromisso6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso6MouseEntered

    private void botaoDeleteCompromisso6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso6MouseExited

    private void botaoDeleteCompromisso6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso6ActionPerformed

    private void botaoDeleteCompromisso7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso7MouseEntered

    private void botaoDeleteCompromisso7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso7MouseExited

    private void botaoDeleteCompromisso7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteCompromisso7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeleteCompromisso7ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
        
        Agenda a;
		a = new Agenda();

		Contato cb;
		cb = new Contato("Teste", new GregorianCalendar(1980, 10, 28));
		cb.setTelefone(new Telefone("3333-5555", "Telefone residencial"));
		cb.setTelefone(new Telefone("99111-1111", "Telefone celular"));
		a.inserir(cb);
               
		a.inserir(
				new EContato("Exemplo", new GregorianCalendar(1975, 2, 22), "exemplo@gmail.com", "www.exemplo.com.br"));

		ContatoBasico obj = a.buscar("Teste"); // pesquisa por nome

		if (obj != null)
			mostraDados(obj);
		else
			System.out.println("Contato nao encontrado!");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoPagina;
    private javax.swing.JButton botaoDeleteCompromisso1;
    private javax.swing.JButton botaoDeleteCompromisso2;
    private javax.swing.JButton botaoDeleteCompromisso3;
    private javax.swing.JButton botaoDeleteCompromisso4;
    private javax.swing.JButton botaoDeleteCompromisso5;
    private javax.swing.JButton botaoDeleteCompromisso6;
    private javax.swing.JButton botaoDeleteCompromisso7;
    private javax.swing.JButton botaoSalvaCompromissos;
    private javax.swing.JButton botaoVoltaDiaAtual;
    private javax.swing.JTextField compromisso1;
    private javax.swing.JTextField compromisso2;
    private javax.swing.JTextField compromisso3;
    private javax.swing.JTextField compromisso4;
    private javax.swing.JTextField compromisso5;
    private javax.swing.JTextField compromisso6;
    private javax.swing.JTextField compromisso7;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d11;
    private javax.swing.JLabel d12;
    private javax.swing.JLabel d13;
    private javax.swing.JLabel d14;
    private javax.swing.JLabel d15;
    private javax.swing.JLabel d16;
    private javax.swing.JLabel d17;
    private javax.swing.JLabel d18;
    private javax.swing.JLabel d19;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d20;
    private javax.swing.JLabel d21;
    private javax.swing.JLabel d22;
    private javax.swing.JLabel d23;
    private javax.swing.JLabel d24;
    private javax.swing.JLabel d25;
    private javax.swing.JLabel d26;
    private javax.swing.JLabel d27;
    private javax.swing.JLabel d28;
    private javax.swing.JLabel d29;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d30;
    private javax.swing.JLabel d31;
    private javax.swing.JLabel d32;
    private javax.swing.JLabel d33;
    private javax.swing.JLabel d34;
    private javax.swing.JLabel d35;
    private javax.swing.JLabel d36;
    private javax.swing.JLabel d37;
    private javax.swing.JLabel d38;
    private javax.swing.JLabel d39;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d40;
    private javax.swing.JLabel d41;
    private javax.swing.JLabel d42;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel d9;
    private javax.swing.JLabel diaPagina;
    private javax.swing.JLabel domFixo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel mesPagina;
    private javax.swing.JLabel quaFixo;
    private javax.swing.JLabel quiFixo;
    private javax.swing.JLabel sabFixo;
    private javax.swing.JLabel segFixo;
    private javax.swing.JComboBox<String> selecaoAno;
    private javax.swing.JComboBox<String> selecaoMes;
    private javax.swing.JLabel semanaPagina;
    private javax.swing.JLabel sexFixo;
    private javax.swing.JLabel terFixo;
    // End of variables declaration//GEN-END:variables

    // construção do calendário
    public void iniciaCalendario(){
        SimpleDateFormat Ano = new SimpleDateFormat("yyyy"); 
        SimpleDateFormat Mes = new SimpleDateFormat("MM"); 
        SimpleDateFormat Dia = new SimpleDateFormat("dd"); 
        
        anoFixo = Integer.parseInt(Ano.format (new Date()));
        mesFixo = Integer.parseInt(Mes.format (new Date()));
        diaFixo = Integer.parseInt(Dia.format (new Date()));
        
        //JOptionPane.showMessageDialog(null, diaFixo+"/"+mesFixo+"/"+anoFixo);
        
        int anoMaximo = anoFixo +50;
        for (int i = 2000; i< anoMaximo; i++){
            selecaoAno.addItem(String.valueOf(i));
        }
        selecaoAno.setSelectedItem(anoFixo);
        
        switch (mesFixo) {
            case 1 -> selecaoMes.setSelectedIndex(0);
            case 2 -> selecaoMes.setSelectedIndex(1);
            case 3 -> selecaoMes.setSelectedIndex(2);
            case 4 -> selecaoMes.setSelectedIndex(3);
            case 5 -> selecaoMes.setSelectedIndex(4);
            case 6 -> selecaoMes.setSelectedIndex(5);
            case 7 -> selecaoMes.setSelectedIndex(6);
            case 8 -> selecaoMes.setSelectedIndex(7);
            case 9 -> selecaoMes.setSelectedIndex(8);
            case 10 -> selecaoMes.setSelectedIndex(9);
            case 11 -> selecaoMes.setSelectedIndex(10);
            case 12 -> selecaoMes.setSelectedIndex(11);
            default -> {
            }
        }
    }
    
    public void semTexto(javax.swing.JLabel a){
        a.setText("");
    }
    
    public void setTextMaisi(javax.swing.JLabel a, int i){
        a.setText("" + i);
    }
    
    public void ifMudaCor(javax.swing.JLabel a, int i){
        if (i == diaFixo & mesAltera == mesFixo -1 & anoAltera == anoFixo){
            a.setForeground(Color.red);
        } else {
            a.setForeground(Color.BLACK);
        }
                
    }
    
    public void fundoOpaco (javax.swing.JLabel a){
        if (!"".equals(a.getText())){
            a.setOpaque(true);
        } else {
            a.setOpaque(false);
        }
    }
    
    public void calendario(){
        
        semTexto(d1);
        semTexto(d2);
        semTexto(d3);
        semTexto(d4);
        semTexto(d5);
        semTexto(d6);
        semTexto(d7);
        semTexto(d8);
        semTexto(d9);
        semTexto(d10);
        semTexto(d11);
        semTexto(d12);
        semTexto(d13);
        semTexto(d14);
        semTexto(d15);
        semTexto(d16);
        semTexto(d17);
        semTexto(d18);
        semTexto(d19);
        semTexto(d20);
        semTexto(d21);
        semTexto(d22);
        semTexto(d23);
        semTexto(d24);
        semTexto(d25);
        semTexto(d26);
        semTexto(d27);
        semTexto(d28);
        semTexto(d29);
        semTexto(d30);
        semTexto(d31);
        semTexto(d32);
        semTexto(d33);
        semTexto(d34);
        semTexto(d35);
        semTexto(d36);
        semTexto(d37);
        semTexto(d38);
        semTexto(d39);
        semTexto(d40);
        semTexto(d41);
        semTexto(d42);


        diaAltera = diaFixo;
        mesAltera = selecaoMes.getSelectedIndex();
        anoAltera = Integer.parseInt(selecaoAno.getSelectedItem().toString());
        
        int totalDiaMes = 0;
        switch (mesAltera) {
            case 0 -> totalDiaMes = 31;
            case 1 -> {
                int resultado = (anoAltera % 4);
                if (resultado ==0){
                    totalDiaMes = 29; // ano bissesto
                } else {
                    totalDiaMes = 28; // não bissesto
                }
            }
            case 2, 4, 6, 7, 9, 11 -> totalDiaMes = 31;
            case 3, 5, 8, 10 -> totalDiaMes = 30;
            default -> {
            }
        }
        
        Calendar calendar = Calendar.getInstance();
        calendar.set (anoAltera, mesAltera, 1);
        int setaDia = 0;
        
        int semana = calendar.get(Calendar.DAY_OF_WEEK);
        switch (semana) {
            case Calendar.SUNDAY -> setaDia = 1; //domingo
            case Calendar.MONDAY -> setaDia = 2; //segunda
            case Calendar.TUESDAY -> setaDia = 3; //terça
            case Calendar.WEDNESDAY -> setaDia = 4; //quarta
            case Calendar.THURSDAY -> setaDia = 5; //quinta
            case Calendar.FRIDAY -> setaDia = 6; //sexta
            case Calendar.SATURDAY -> setaDia = 7; //sábado
            default -> {
            }
        }
        
        
        
        for (int i = 1; i <= totalDiaMes; i++){
            switch (setaDia){
                case 1 -> setTextMaisi(d1, i);
                case 2 -> {
                    setTextMaisi(d2, i);
                    ifMudaCor(d2, i);
                }
                case 3 -> {
                    setTextMaisi(d3, i);
                    ifMudaCor(d3, i);
                }
                case 4 -> {
                    setTextMaisi(d4, i);
                    ifMudaCor(d4, i);
                }
                case 5 -> {
                     setTextMaisi(d5, i);
                    ifMudaCor(d5, i);
                }
                case 6 -> {
                     setTextMaisi(d6, i);
                    ifMudaCor(d6, i);
                }
                case 7 -> {
                     setTextMaisi(d7, i);
                    ifMudaCor(d7, i);
                }
                case 8 -> {
                     setTextMaisi(d8, i);
                    ifMudaCor(d8, i);
                }
                case 9 -> {
                     setTextMaisi(d9, i);
                    ifMudaCor(d9, i);
                }
                case 10 -> {
                     setTextMaisi(d10, i);
                    ifMudaCor(d10, i);
                }
                case 11 -> {
                     setTextMaisi(d11, i);
                    ifMudaCor(d11, i);
                }
                case 12 -> {
                     setTextMaisi(d12, i);
                    ifMudaCor(d12, i);
                }
                case 13 -> {
                     setTextMaisi(d13, i);
                    ifMudaCor(d13, i);
                }
                case 14 -> {
                     setTextMaisi(d14, i);
                    ifMudaCor(d14, i);
                }
                case 15 -> {
                     setTextMaisi(d15, i);
                    ifMudaCor(d15, i);
                }
                case 16 -> {
                     setTextMaisi(d16, i);
                    ifMudaCor(d16, i);
                }
                case 17 -> {
                     setTextMaisi(d17, i);
                    ifMudaCor(d17, i);
                }
                case 18 -> {
                     setTextMaisi(d18, i);
                    ifMudaCor(d18, i);
                }
                case 19 -> {
                    setTextMaisi(d19, i);
                    ifMudaCor(d19, i);
                }
                case 20 -> {
                     setTextMaisi(d20, i);
                    ifMudaCor(d20, i);
                }
                case 21 -> {
                     setTextMaisi(d21, i);
                    ifMudaCor(d21, i);
                }
                case 22 -> {
                     setTextMaisi(d22, i);
                    ifMudaCor(d22, i);
                }
                case 23 -> {
                    setTextMaisi(d23, i);
                    ifMudaCor(d23, i);
                }
                case 24 -> {
                     setTextMaisi(d24, i);
                    ifMudaCor(d24, i);
                }
                case 25 -> {
                     setTextMaisi(d25, i);
                    ifMudaCor(d25, i);
                }
                case 26 -> {
                     setTextMaisi(d26, i);
                    ifMudaCor(d26, i);
                }
                case 27 -> {
                     setTextMaisi(d27, i);
                    ifMudaCor(d27, i);
                }
                case 28 -> {
                     setTextMaisi(d28, i);
                    ifMudaCor(d28, i);
                }
                case 29 -> {
                     setTextMaisi(d29, i);
                    ifMudaCor(d29, i);
                }
                case 30 -> {
                     setTextMaisi(d30, i);
                    ifMudaCor(d30, i);
                }
                case 31 -> {
                     setTextMaisi(d31, i);
                    ifMudaCor(d31, i);
                }
                case 32 -> {
                     setTextMaisi(d32, i);
                    ifMudaCor(d32, i);
                }
                case 33 -> {
                     setTextMaisi(d33, i);
                    ifMudaCor(d33, i);
                }
                case 34 -> {
                     setTextMaisi(d34, i);
                    ifMudaCor(d34, i);
                }
                case 35 -> {
                     setTextMaisi(d35, i);
                    ifMudaCor(d35, i);
                }
                case 36 -> {
                     setTextMaisi(d36, i);
                    ifMudaCor(d36, i);
                }
                case 37 -> {
                     setTextMaisi(d37, i);
                    ifMudaCor(d37, i);
                }
                case 38 -> {
                     setTextMaisi(d38, i);
                    ifMudaCor(d38, i);
                }
                case 39 -> {
                     setTextMaisi(d39, i);
                    ifMudaCor(d39, i);
                }
                case 40 -> {
                    setTextMaisi(d40, i);
                    ifMudaCor(d40, i);
                }
                case 41 -> {
                     setTextMaisi(d41, i);
                    ifMudaCor(d41, i);
                }
                case 42 -> {
                    setTextMaisi(d42, i);
                    ifMudaCor(d42, i);
                }    
    
    
         
            }
            setaDia ++;
        }
        
        fundoOpaco(d1);
        fundoOpaco(d2);
        fundoOpaco(d3);
        fundoOpaco(d4);
        fundoOpaco(d5);
        fundoOpaco(d6);
        fundoOpaco(d7);
        fundoOpaco(d8);
        fundoOpaco(d9);
        fundoOpaco(d10);
        fundoOpaco(d11);
        fundoOpaco(d12);
        fundoOpaco(d13);
        fundoOpaco(d14);
        fundoOpaco(d15);
        fundoOpaco(d16);
        fundoOpaco(d17);
        fundoOpaco(d18);
        fundoOpaco(d19);
        fundoOpaco(d20);
        fundoOpaco(d21);
        fundoOpaco(d22);
        fundoOpaco(d23);
        fundoOpaco(d24);
        fundoOpaco(d25);
        fundoOpaco(d26);
        fundoOpaco(d27);
        fundoOpaco(d28);
        fundoOpaco(d29);
        fundoOpaco(d30);
        fundoOpaco(d31);
        fundoOpaco(d32);
        fundoOpaco(d33);
        fundoOpaco(d34);
        fundoOpaco(d35);
        fundoOpaco(d36);
        fundoOpaco(d37);
        fundoOpaco(d38);
        fundoOpaco(d39);
        fundoOpaco(d40);
        fundoOpaco(d41);
        fundoOpaco(d42);

            
        verificaSemana();
        
    }            
     
    public void verificaSemana(){
        
        if (mesAltera != mesFixo-1 & diaClick !=0){
            diaAltera = 1;
        }
        if (anoAltera != anoFixo & diaClick !=0){
            diaAltera = 1;
        }
        diaClick = 1;
        
        if(diaAltera == diaFixo & mesAltera +1 == mesFixo & anoAltera == anoFixo){
            diaPagina.setForeground(Color.red);
        } else {
            diaPagina.setForeground(Color.black);
        }
        
        mesAltera = selecaoMes.getSelectedIndex();
        anoAltera = Integer.parseInt(selecaoAno.getSelectedItem().toString());
        
        Calendar calendarN = Calendar.getInstance();
        calendarN.set (anoAltera, mesAltera, diaAltera);
        
        mesPagina.setText(selecaoMes.getSelectedItem().toString());
        diaPagina.setText(""+diaAltera);
        
        int semanaN = calendarN.get(Calendar.DAY_OF_WEEK);
        switch (semanaN) {
            case Calendar.SUNDAY -> semanaPagina.setText("Domingo");
            case Calendar.MONDAY -> semanaPagina.setText("Segunda");
            case Calendar.TUESDAY -> semanaPagina.setText("Terça");
            case Calendar.WEDNESDAY -> semanaPagina.setText("Quarta");
            case Calendar.THURSDAY -> semanaPagina.setText("Quinta");
            case Calendar.FRIDAY -> semanaPagina.setText("Sexta");
            case Calendar.SATURDAY -> semanaPagina.setText("Sábado");
            default -> {
            }
        }
    }
    
    public void eventosMouse(javax.swing.JLabel a){
       
        a.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseEntered(java.awt.event.MouseEvent evt){
               if (!"".equals(a.getText())){
                   a.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
               }
           }
           public void mouseExited(java.awt.event.MouseEvent evt){
               a.setBorder(null);
           } 
           public void mouseClicked(java.awt.event.MouseEvent evt){
               if (!"".equals(a.getText())){
                   diaPagina.setText(a.getText());
                   diaAltera = Integer.parseInt(a.getText());
                   diaClick = 0;
                   verificaSemana();
                   //leAgenda();
               }
           }
        });
         
    }
        
    public void calendarioEventosMouse(){
        
        eventosMouse(d1);
        eventosMouse(d2);
        eventosMouse(d3);
        eventosMouse(d4);
        eventosMouse(d5);
        eventosMouse(d6);
        eventosMouse(d7);
        eventosMouse(d8);
        eventosMouse(d9);
        eventosMouse(d10);
        eventosMouse(d11);
        eventosMouse(d12);
        eventosMouse(d13);
        eventosMouse(d14);
        eventosMouse(d15);
        eventosMouse(d16);
        eventosMouse(d17);
        eventosMouse(d18);
        eventosMouse(d19);
        eventosMouse(d20);
        eventosMouse(d21);
        eventosMouse(d22);
        eventosMouse(d23);
        eventosMouse(d24);
        eventosMouse(d25);
        eventosMouse(d26);
        eventosMouse(d27);
        eventosMouse(d28);
        eventosMouse(d29);
        eventosMouse(d30);
        eventosMouse(d31);
        eventosMouse(d32);
        eventosMouse(d33);
        eventosMouse(d34);
        eventosMouse(d35);
        eventosMouse(d36);
        eventosMouse(d37);
        eventosMouse(d38);
        eventosMouse(d39);
        eventosMouse(d40);
        eventosMouse(d41);
        eventosMouse(d42);
    }
    

    
}
        
        
        
        
        
        
        
    
    

